claim, change owner contracts
cryptoviet/gafi-app pull request #15
Opened 2022-06-02 10:20 UTC by nhathoang241199

1. UI

Add contracts page:
![image](https://user-images.githubusercontent.com/66844113/171608671-b9eab493-a639-4308-b440-80512a04aab9.png)

Claim form:
![image](https://user-images.githubusercontent.com/66844113/171608740-4b87a80e-3414-4b48-bba7-5eab233d611f.png)

Listing contracts:
![image](https://user-images.githubusercontent.com/66844113/171608804-ae06c0ac-f294-4c7f-a572-2ff6d6cf888d.png)

Change owner form:
![image](https://user-images.githubusercontent.com/66844113/171608844-f629dbe2-b81a-415e-b6ef-a9dc59a64cde.png)

2. Overview
- Claim contract
- Listing contracts
- Change contract owner
- Load set init polkadot account that is map with metamask account.

2022-06-03 03:33 UTC, lhtrung307 requested changes

2022-06-03 03:33 UTC, lhtrung307 commented on src/components/navbars/AdminNavbarLinks.tsx
> +  const Pairs = keyring?.getPairs() || [];
Should follow naming convention.

2022-06-03 03:33 UTC, lhtrung307 commented on src/components/navbars/UserMenu.tsx
> +                          {accountList?.map(
This will have warning about key prop.

2022-06-03 03:33 UTC, lhtrung307 commented on src/pages/Contracts/Contracts.tsx
> +      .then(data => {
Should use async await.

2022-06-03 03:33 UTC, lhtrung307 commented on src/pages/Contracts/Contracts.tsx
> +          data.forEach(([key, exposure]) => {
Using `map` to return new array instead of pushing data into variable.

2022-06-03 03:33 UTC, lhtrung307 commented on src/pages/Contracts/Contracts.tsx
> +        title="Contracts"
Translate.

2022-06-03 03:33 UTC, lhtrung307 commented on src/pages/Contracts/Contracts.tsx
> +  useEffect(() => {
Using `react-query` instead.

2022-06-03 03:33 UTC, lhtrung307 commented on src/pages/Contracts/components/ContractTable.tsx
> +  contracts: IResponseContract[] | undefined;
Using `contracts?:` instead.

2022-06-03 03:33 UTC, lhtrung307 commented on src/pages/Contracts/components/ContractTable.tsx
> +  children: React.ReactNode;
Using `React.FC` will have default children prop.

2022-06-03 03:33 UTC, lhtrung307 commented on src/pages/Contracts/components/ContractTable.tsx
> +      <CardHeader p="6px 0px 22px 0px">
Use chakra spacing.

2022-06-03 03:33 UTC, lhtrung307 commented on src/pages/Contracts/components/ContractTable.tsx
> +            <Tr my=".8rem" pl="0px" color="gray.400">
Use chakra spacing.

2022-06-03 03:33 UTC, lhtrung307 commented on src/pages/Contracts/components/ModalChangeContractOwner.tsx
> +                id="discount"
Using id `discount`?

2022-06-03 04:11 UTC, lhtrung307 requested changes

2022-06-03 04:11 UTC, lhtrung307 commented on src/components/navbars/AdminNavbarLinks.tsx
> +    const polkadotAccount = response?.toHuman()?.toString() || '';
Why do we need to use `toHuman` and then `toString`?

2022-06-03 04:11 UTC, lhtrung307 commented on src/components/navbars/AdminNavbarLinks.tsx
> +    const initPair = pairs?.find(
Do we need `?` here?

2022-06-03 04:11 UTC, lhtrung307 commented on src/components/navbars/AdminNavbarLinks.tsx
> +  const accountList = pairs?.map((key: KeyringPair) => acctAddr(key));
Do we need `?` here?

2022-06-03 04:11 UTC, lhtrung307 commented on src/components/navbars/AdminNavbarLinks.tsx
> +      setCurrentAccount(pairs[0]);
What's gonna happen if `pairs` is empty?

2022-06-03 05:16 UTC, nhathoang241199 commented on src/components/navbars/AdminNavbarLinks.tsx
> +    const polkadotAccount = response?.toHuman()?.toString() || '';
in begin I want to make sure polkadotAccount is a string. But in fact it not necessary.

2022-06-03 05:17 UTC, nhathoang241199 commented on src/components/navbars/AdminNavbarLinks.tsx
> +    const initPair = pairs?.find(
nope!

2022-06-06 02:24 UTC, lhtrung307 approved these changes

2022-06-06 02:31 UTC, merged