add dashboard layout
cryptoviet/gafi-app pull request #23
Opened 2022-06-09 10:47 UTC by nhathoang241199

Dashboard layout include:

1. Sidebar
![image](https://user-images.githubusercontent.com/66844113/172828998-e5caaf1e-11a1-42e9-820a-40c534e10466.png)

2. Panel
![image](https://user-images.githubusercontent.com/66844113/172829087-885d7c76-0e58-4fd5-ac70-a9051ec43b2c.png)

3. AccountInfo
![image](https://user-images.githubusercontent.com/66844113/172829153-c4dadc73-382d-46d9-88db-8c116b8131c4.png)

And banner component: (isn't belong to layout) 
![image](https://user-images.githubusercontent.com/66844113/172829249-da7d3bee-8fd9-435d-87a8-fe9fe8b49f57.png)

2022-06-09 11:41 UTC, satoshiman commented
2 icon day/night mode & send (I don't know the purpose) do not need white background 
<img width="237" alt="image" src="https://user-images.githubusercontent.com/37683529/172837409-8cc41888-206f-481e-abb8-aa7191746c06.png">

It's better if we use `monospace font` for wallet address format
<img width="332" alt="image" src="https://user-images.githubusercontent.com/37683529/172837836-86866c8f-d989-43d4-91c4-422907945162.png">

Add `GAKI` unit after the balance (or Your balance => Your GAKI balance)

Change `Faucet` CTA => `Request testnet GAKI` 

It seems responsive wasn't applied to this layout?

2022-06-10 03:02 UTC, lhtrung307 requested changes

2022-06-10 03:02 UTC, lhtrung307 commented on src/routes.tsx
>      name: 'Dashboard',
Should translate these too.

2022-06-10 09:05 UTC, lhtrung307 commented on src/layouts/DashboardLayout/DashboardLayout.tsx
> +        flexDirection: 'column',
Redundant style.

2022-06-10 09:06 UTC, lhtrung307 commented on src/layouts/DashboardLayout/components/AccountInfo.tsx
> +        console.log('error: ', error);
Show a toast for this.

2022-06-13 03:33 UTC, lhtrung307 approved these changes

2022-06-13 03:34 UTC, merged