responsive layout
cryptoviet/gafi-app pull request #56
Opened 2022-06-27 11:00 UTC by nhathoang241199

Responsive layout
Refactor logic code
Responsive upfront pool page
Responsive banner component

2022-06-28 03:30 UTC, lhtrung307 requested changes

2022-06-29 03:02 UTC, lhtrung307 requested changes

2022-06-29 03:02 UTC, lhtrung307 commented on src/index.tsx
> +// import 'fonts/Helvetica-Font/Helvetica-Bold.ttf';
Remove comment.

2022-06-29 03:02 UTC, lhtrung307 commented on src/hooks/useUpfrontPool.ts
> +        try {
Duplicate code. Should refactor.

2022-06-29 03:02 UTC, lhtrung307 commented on src/hooks/useUpfrontPool.ts
> +        try {
Duplicate code. Should refactor.

2022-06-29 03:02 UTC, lhtrung307 commented on src/hooks/useUpfrontPool.ts
> +  const pools: Array<IPool> = [
Should not put pool table info inside of this hook.

2022-06-29 03:12 UTC, nhathoang241199 commented on src/layouts/DashboardLayout/components/Panel.tsx
> +          icon={<Icon size={1.5} path={mdiMenu} color={theme.colors.primary} />}
"primary" dont work in this case.

2022-06-29 03:15 UTC, nhathoang241199 commented on src/themes/theme.tsx
> +    tablet: '740px',
No, It doesnt. I customized them.

2022-06-29 07:09 UTC, lhtrung307 requested changes

2022-06-29 07:09 UTC, lhtrung307 commented on src/layouts/DashboardLayout/components/Panel.tsx
> +  borderBottom: { base: '2px solid #EEF1FF', pc: 'none' },
Should use color variable here, too.

2022-06-29 07:27 UTC, lhtrung307 approved these changes

2022-06-29 07:42 UTC, merged