reponsive dashboard page
cryptoviet/gafi-app pull request #57
Opened 2022-06-29 11:00 UTC by nhathoang241199

- Responsive dashboard page.

2022-06-30 03:09 UTC, lhtrung307 requested changes

2022-06-30 03:09 UTC, lhtrung307 commented on src/pages/Dashboard/components/EventInfo.tsx
> +              <Box sx={eventContent} alignItems="flex-start">
`alignItems="flex-start"` without `flex`?

2022-06-30 03:09 UTC, lhtrung307 commented on src/pages/Dashboard/components/EventInfo.tsx
> +      <Box alignItems="flex-start">
`flex-start` without `flex`?

2022-06-30 03:09 UTC, lhtrung307 commented on src/pages/Dashboard/components/EventInfo.tsx
> +    <Card display="flex" flexDirection="column">
`Card` already has this style.

2022-06-30 03:09 UTC, lhtrung307 commented on src/pages/Dashboard/Dashboard.tsx
> +              <HStack w="full" py={5} borderTop="1px solid #EEF1FF">
Color variable.

2022-07-01 03:48 UTC, lhtrung307 requested changes

2022-07-01 03:48 UTC, lhtrung307 commented on src/components/SkeletonLoadingRow/SkeletonLoadingRow.tsx
> +  const columnArray = new Array(isMobile ? 3 : columnAmount).fill(0);
Should move this logic outside of component.

2022-07-01 03:48 UTC, lhtrung307 commented on src/components/pagination/Pagination.tsx
> +        tablet: isSmallScreen ? 'column' : 'row',
Using double media query? `tablet` is a media query already.

2022-07-01 03:48 UTC, lhtrung307 commented on src/components/pagination/Pagination.tsx
> +          {!!totalCount && isMobile ? null : (
Create a variable for this.

2022-07-01 03:48 UTC, lhtrung307 commented on src/components/sideBar/Faucet.tsx
> +        position: 'top-right',
Should consistence with another toast.

2022-07-01 03:48 UTC, lhtrung307 commented on src/contexts/substrateContext/substrateContext.tsx
> +  const [isMobile] = useMediaQuery('(max-width: 739px)');
Too many type of media query. Should follow defined breakpoints.

2022-07-01 03:48 UTC, lhtrung307 commented on src/hooks/useChangeOwner.ts
> +import { useMediaQuery, useToast } from '@chakra-ui/react';
`useMediaQuery` is not used anywhere. Remove it.

2022-07-01 03:48 UTC, lhtrung307 commented on src/hooks/useClaimContract.ts
> +import { useMediaQuery, useToast } from '@chakra-ui/react';
Same here.

2022-07-01 03:48 UTC, lhtrung307 commented on src/hooks/useCreatePool.ts
> +import { useMediaQuery, useToast } from '@chakra-ui/react';
Same here.

2022-07-01 03:48 UTC, lhtrung307 commented on src/hooks/useFaucet.ts
> +  const [isMobile] = useMediaQuery('(max-width: 739px)');
Do we need this?

2022-07-01 03:48 UTC, lhtrung307 commented on src/hooks/usePool.ts
> +      setLoadingPool(poolPackage || '');
Why do we have to use `|| ''` here?

2022-07-01 03:48 UTC, lhtrung307 commented on src/hooks/usePool.ts
> +  const mutation = useMutation(
Too many things in one hook.

2022-07-01 03:48 UTC, lhtrung307 commented on src/pages/Dashboard/components/EventInfo.tsx
> +            borderTop={
Should check the stack divider feature.

2022-07-01 03:48 UTC, lhtrung307 commented on src/pages/SponsoredPool/components/SponsoredPoolTableRow.tsx
> +import { t } from 'i18next';
Wrong import.

2022-07-01 03:48 UTC, lhtrung307 commented on src/pages/SponsoredPool/SponsoredPool.tsx
> +          isMobile || isSmallScreen
Maybe we can have the `display` attribute for the table column.

2022-07-01 03:48 UTC, lhtrung307 commented on src/pages/SponsoredPool/components/SponsoredPoolTableRow.tsx
> +              w={{ base: 10, pc: isSmallScreen ? 10 : 14 }}
Double media query.

2022-07-01 03:48 UTC, lhtrung307 commented on src/pages/SponsoredPool/components/SponsoredPoolTableRow.tsx
> +          <Td
We can use detail as table action.

2022-07-01 03:48 UTC, lhtrung307 commented on src/pages/SponsoredPool/components/SponsoredPoolTableRow.tsx
> +                  chainDecimal || 18
`chainDecimal` already have the default value.

2022-07-01 03:48 UTC, lhtrung307 commented on src/utils/utils.ts
> +  if (length) return `${hash.substr(0, length)}...${hash.substr(n - length)}`;
We can provide the default value for length as 6

2022-07-01 05:02 UTC, nhathoang241199 commented on src/components/SkeletonLoadingRow/SkeletonLoadingRow.tsx
> +  const columnArray = new Array(isMobile ? 3 : columnAmount).fill(0);
Can you suggest a place to move

2022-07-01 05:05 UTC, lhtrung307 commented on src/components/SkeletonLoadingRow/SkeletonLoadingRow.tsx
> +  const columnArray = new Array(isMobile ? 3 : columnAmount).fill(0);
You can move it to the parent component.

2022-07-01 05:05 UTC, nhathoang241199 commented on src/components/pagination/Pagination.tsx
> +        tablet: isSmallScreen ? 'column' : 'row',
I want in small screen [1024px - 1400px] , the direction is 'column'. Tablet is (>= 740)

2022-07-01 07:00 UTC, nhathoang241199 commented on src/pages/SponsoredPool/components/SponsoredPoolTableRow.tsx
> +              w={{ base: 10, pc: isSmallScreen ? 10 : 14 }}
pc (> 1024px) isn't same pc and smallScreen (> 1024px && (1024 - 1400))

2022-07-01 07:09 UTC, lhtrung307 commented on src/components/pagination/Pagination.tsx
> +        tablet: isSmallScreen ? 'column' : 'row',
If you want that, you can write like this: `tablet: 'row', pc: 'column'`.

2022-07-01 07:14 UTC, lhtrung307 commented on src/pages/SponsoredPool/components/SponsoredPoolTableRow.tsx
> +              w={{ base: 10, pc: isSmallScreen ? 10 : 14 }}
Same here. It's just the way you use it.

2022-07-01 09:33 UTC, nhathoang241199 commented on src/components/pagination/Pagination.tsx
> +        tablet: isSmallScreen ? 'column' : 'row',
but pc is > 1024px. I don't want the screen larger than 1400px is styled.

2022-07-05 03:37 UTC, lhtrung307 approved these changes

2022-07-05 03:38 UTC, merged