listing sponsored pools + fix discount in staking page
cryptoviet/gafi-app pull request #8
Opened 2022-05-18 10:00 UTC by nhathoang241199

The sponsored pool table like this:

![image](https://user-images.githubusercontent.com/66844113/169012956-3581aae7-6888-4aee-a5e4-2d66c85a388e.png)

Fix display wrong discount percen:

![image](https://user-images.githubusercontent.com/66844113/169013197-d05ffe4e-79b5-4aa1-8489-0b43feec8425.png)

The directory structure is as follows:

![image](https://user-images.githubusercontent.com/66844113/169013466-858d4253-a06a-4ae2-bedb-d3fef69b0fad.png)

2022-05-20 13:52 UTC, lhtrung307 requested changes

2022-05-20 13:52 UTC, lhtrung307 commented on src/pages/SponsoredPool/components/ModalAddSponsoredPool.tsx
> +    console.log('pageNumberOfNewPool: ', pageNumberOfNewPool)
Remove log.

2022-05-20 14:15 UTC, nhathoang241199 commented on src/pages/SponsoredPool/components/SponsoredPoolPagination.tsx
> +  for (let i = 1; i <= totalPage; i++) {
you mean " for (let i = 0; i < totalPage; i++) " ?

2022-05-20 14:19 UTC, nhathoang241199 commented on src/pages/SponsoredPool/components/SponsoredPoolPagination.tsx
> +              Showing <b> {{totalCount}} </b> of <b> {{totalCount}} </b> results
Because if we have 2 results/page and 9 total result, the message will like:
- In page 2: "Showing 2 to 4 of 9 results"
- In last page( page 5 ): "Showing 9 of 9 results"

2022-05-26 02:18 UTC, lhtrung307 approved these changes

2022-05-26 02:33 UTC, merged